### ISSUE TITLE
CNAs must provide a scope page on their website

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#14]
GOAL: Make CNA scope more easily determined by third parties.
CHANGE: Add a rule that states a CNA must provide a page on their web site which lists the products for which they accept vulnerability reports. This includes a listing of EOL (or other) software that are explicitly _not_ covered.
OUTCOME: CNA scopes will be easy to find by anyone.

**Comment by tuchiyama** [comment]
Maybe limit this to vendor CNA's?

Researchers and third-party coordinators typically do not have a list of products as a defined scope.

**Comment by kurtseifried** [comment]
make CNA define coverage:
https://github.com/distributedweaknessfiling/DWF-CNA-Registry/blob/master/CNA-Registry/000000/cna-4.json

  "CNA_coverage": [
    {
      "common_vendor_name": "Kubernetes",
      "common_product_name": "Kubernetes",
      "common_url": "https://github.com/kubernetes/",
      "common_url_includes_sub_urls": true
    }
  ],

I would definitely be willing to add a "lifecycle_status" value or something (supported, critical_only, eol, etc.) but we'd want to define those terms.

**Comment by dadinolfi** [comment]
This should be a universal requirement, not just for vendors or projects. If there isn't some kind of scoping statement, it increases ambiguity. One goal of this is to reduce ambiguity in the minds of those not intimately familiar with the program.

Vendors and projects should offer a blanket statement, a list of specific things covered, or a list of specific things not covered (or a mix of covered and not covered).

Researchers and third-party coordinators should have something as well. Theirs could say "we will issue CVE IDs for products or projects that we are researching unless they are otherwise covered by another CNA". This would help direct folks away from them as a source for a CVE ID in anything in particular and instead point them to the proper CNA (or up to the Primary).

We want the published scope to be updated whenever a CNA's scope changes. Scope may change due to the introduction of new projects or products, end-of-life'd projects or products, mergers/sales/acquisitions at the company level, or a change in process. We should put the responsibility for tracking these changes on the CNA instead of asking a Root or the Primary since, often, these changes happen without the Root or Primary noticing. The Root and Primary can then point to that information from a common directory without having to maintain the content itself.

**Comment by dadinolfi** [comment]
Suggestion: Add section 2.2.11

A CNA must provide a URL to a list the products for which they accept vulnerability reports, which is referred to as their "scope". When defining their scope, vendors and development projects should offer a blanket statement (e.g., "All of Company X's products"), a list of specific things covered, or a list of specific things not covered (or a mix of covered and not covered). For researchers and third-party coordinators, theirs might say "we will issue CVE IDs for products or projects that we are researching unless they are otherwise covered by another CNA". This would help direct folks away from them as a source for a CVE ID in anything in particular and instead point them to the proper CNA (or up to the Primary). The published scope must be updated whenever a CNA's scope changes. Scope may change due to the introduction of new projects or products; projects or products being set to "end-of-life" status; mergers, sales, or acquisitions at a company level; or a change in process.
