### ISSUE TITLE
Define requirements for disclosure policies

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#16]
GOAL: Make CNA scope more easily determined by third parties
CHANGE: Clarify the difference between "when a vulnerability is made public" versus "when a vulnerability is added to the CVE list" and how they affect each other.
OUTCOME: Everyone will know what is and isn't covered by a CNA.

GOAL: 
CHANGE: Clarify disclosure policies and what kinds of vulnerabilities (public, non-public, etc.) are given CVE IDs by the CNA and for what specific scope. Include a policy template. (Review the Embargo and Disclosure template)
OUTCOME:

**Comment by kurtseifried** [comment]
CNA scope should be define clearly in their CNA registry doc, e.g.:

https://github.com/distributedweaknessfiling/DWF-CNA-Registry/blob/master/CNA-Registry/000000/cna-4.json

"CNA_coverage": [
    {
      "common_vendor_name": "Kubernetes",
      "common_product_name": "Kubernetes",
      "common_url": "https://github.com/kubernetes/",
      "common_url_includes_sub_urls": true
    }
  ],

**Comment by dadinolfi** [comment]
Current definition for "publicly known" in Appendix A:
A vulnerability is publicly known when the issue has been published or divulged publicly (or is scheduled to be published by a researcher or vendor who has been in communication with the CVE Team regarding the issue).

**Comment by dadinolfi** [comment]
From https://github.com/CVEProject/docs/blob/gh-pages/cna/DRAFT%20-%20Information%20Sharing%20and%20Embargo%20Policies.docx we have two example Embargo and Disclosure Policy examples:

MITRE

Requesters are free to use this CNA even if vulnerability information will remain private for an unpredictable amount of time. This CNA accommodates all vulnerability-discovery use cases, including ones in which the discoverer must maintain confidentiality for long periods of time in order to be publicly credited by the vendor. The MITRE CVE project does not offer an opinion about vulnerability-disclosure timelines.
 
The policy of this CNA is that CVE ID requests are not visible to persons with any perceived conflict of interest. CVE ID requests may be read by persons who are MITRE employees and/or contractors. These persons must not work for other organizations that request CVE IDs, use CVE IDs, or produce or sell products that may have CVEs (i.e., customer-controlled products of software or computer hardware). This CNA does not provide any preferential treatment of CVE ID requests that originate within MITRE, or that relate to products produced or used by MITRE.
____ 

DWF

This CNA suggests a vulnerability-disclosure timeline of N days. This CNA reserves the right to discontinue service to requesters if their vulnerability discoveries regularly remain private (to only the discoverer and the vendor) for more than Y days each time.
 
This CNA discloses its directors on the https://github.com/distributedweaknessfiling/DWF-Documentation/blob/master/General-Information.md web page. The directors may read private/embargoed CVE ID requests. Some of the directors are primarily employed by organizations who use CVE IDs extensively to advance their own commercial interests. For example, employers of these directors may sell vulnerability databases that wish to have the earliest possible information or fix product vulnerabilities with a hope of offering the earliest possible fixes. It is up to each requester to decide whether this has any perceived conflict of interest.

**Comment by dadinolfi** [comment]
Suggestion: remove definition for "publicly known" in Appendix A since the following was added to 2.1.1 Assignment Rules:

Note: for a vulnerability to be considered "public", the following conditions must be met:
•	There must be a URL including information about the vulnerability accessible from the internet.
•	The Terms of Use of the website must allow the CVE List to link to the URL.
•	The document linked by the URL must contain the minimum required information for a CVE Entry (see Appendix B).
Registration and login requirements are acceptable, but there cannot be other restrictions for accessing that content. Also, advisories that require payment for access are not considered public. That said, if you have a public advisory with the minimum required details with additional details available through paid access, the vulnerability is still considered public.

**Comment by dadinolfi** [comment]
Suggestion: add a new section to Appendix A called "CVE ID Lifecycle Terminology"

A CVE ID is considered *assigned* when any CNA has assigned that CVE ID to a vulnerability.

A CVE ID is considered *reserved* when
- The CVE ID has been allocated to a CNA for their potential use, or
- The Primary CNA has assigned a CVE ID to a vulnerability for a non-CNA CVE ID requester. 
Note: A reserved CVE ID may be in the reserved state without having been assigned. See https://cve.mitre.org/about/faqs.html#reserved_signify_in_cve_id for more discussion on reserved CVE IDs.

A CVE ID entry is *populated* when the description, references, and other meta information about the entry is added to the CVE List. A CVE ID entry marked as "reserved" or "rejected" is not considered populated.

A CVE ID is *published* when the CVE ID itself is used in a public forum outside of CVE. A CVE ID entry may not be populated when someone publishes the CVE ID. The CVE ID entry will not be populated until the minimal required information for CVE assignment has been communicated to the Primary CNA. Note: if the CVE ID is used publicly before anyone has updated the Primary CNA with the CVE ID information, the CVE ID entry may show as "reserved" or nonexistent in the CVE List until the Primary CNA has been updated.

Note the distinction between CVE IDs that are "published" versus those that are "populated". Published CVE ID exist outside of the CVE list. Populated CVE IDs are those that are found within the CVE List. These two terms help make the distinction between what is and is not included within the official CVE List.

**Comment by dadinolfi** [comment]
Section 2.2.2 indicates that CNAs must "Publish a disclosure (embargo) policy and a description of its scope." (See Issue #14 for discussion on the description of its scope.)

The disclosure/embargo policy could include:
What process a third-party should expect when reporting a vulnerability to the CNA, including when the CNA will assign a CVE ID and when and how they will publish the CVE ID. Also, what expectations there are for the vulnerability reporter as far as their role in the disclosure process.
Communication guidelines and timelines, such as when a reporter should expect a response and what information the CNA is willing to discuss publicly. Just as important, the methods for contacting the CNA should be clearly described.
Guidelines describing what they consider to be vulnerabilities in their products. For example, they can stipulate which version of the CNT2 Counting Rule they use.
If they are involved in a Bug Bounty program, how do the rules of the Bug Bounty program affect their CVE assignment process?

As an example, this is a link to US CERT's vulnerability disclosure policy:
http://www.cert.org/vulnerability-analysis/vul-disclosure.cfm?

**Comment by EvansJonathan** [comment]
Here are some good templates for disclosure policies.  Any one of them would be good for our purposes.

ENISA Good Practice Guide on Vulnerability Disclosure
https://www.enisa.europa.eu/publications/vulnerability-disclosure/at_download/fullReport

ISO/IEC 29147 Vulnerability Disclosure
https://www.iso.org/standard/45170.html

NTIA “Early Stage” Coordinated Vulnerability Disclosure Template
https://www.ntia.doc.gov/files/ntia/publications/ntia_vuln_disclosure_early_stage_template.pdf

Open Source Responsible Disclosure Framework
https://github.com/bugcrowd/disclosure-policy
