### ISSUE TITLE
Use terminology as defined by RFC 2119 (MUST, SHOULD, MAY)

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#23]
GOAL:  Clarify the requirements
CHANGE: Use terminology as defined by RFC 2119
OUTCOME: CNAs will be certain what the requirements are to be CNA.

**Comment by dadinolfi** [comment]
https://www.ietf.org/rfc/rfc2119.txt

1. MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

2. MUST NOT   This phrase, or the phrase "SHALL NOT", mean that the
   definition is an absolute prohibition of the specification.

3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.

5. MAY   This word, or the adjective "OPTIONAL", mean that an item is
   truly optional.  One vendor may choose to include the item because a
   particular marketplace requires it or because the vendor feels that
   it enhances the product while another vendor may omit the same item.
   An implementation which does not include a particular option MUST be
   prepared to interoperate with another implementation which does
   include the option, though perhaps with reduced functionality. In the
   same vein an implementation which does include a particular option
   MUST be prepared to interoperate with another implementation which
   does not include the option (except, of course, for the feature the
   option provides.)

**Comment by dadinolfi** [comment]
If the use of these terms is acceptable, they will be added as appropriate during this and future revisions.

**Comment by kurtseifried** [comment]
+1, can we close this out?

**Comment by todb-r7** [comment]
FWIW I would love to avoid "SHALL" and "SHALL NOT" completely because I think there's a non-zero chance to misinterpret it as a "SHOULD." MUST and MUST NOT strike me as much less ambiguous.

Also, there's only one usage of the word shall in the existing docs, in 2.3.2: "These metrics shall be provided quarterly to the next higher-level CNA. See Appendix G for details."

**Comment by dadinolfi** [comment]
ACK. I will update 2.3.2 with MUST instead of shall.
