### ISSUE TITLE
Define when an entry should be marked as disputed versus rejected

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#25]
GOAL:  Make the CNA processes more standardized and repeatable.
CHANGE: Define when an entry should be marked as disputed versus rejected.
OUTCOME: Consistent results with defensible reasoning

**Comment by dadinolfi** [comment]
Current language in Appendix E:
Not everyone shares the same definition of a vulnerability. One person’s vulnerability is another person’s security hardening opportunity, and another person’s intended functionality. How does CVE deal with these differing opinions?
When an authoritative source disputes the validity of the vulnerability, “"** DISPUTED **” is added to the beginning of the description, and a short NOTE is added to the end explaining why the vulnerability is disputed. Ideally, the disputing party provides a link that can be added to the CVE as a reference, and a quote that can be used as the explanation in the NOTE. However, neither are required.

New, adding a new paragraph to the end:
Note: marking a CVE entry as disputed is different from rejecting a CVE entry. Rejections are made because the issue is clearly not a vulnerability (it fails CNT2), the vulnerability is not made public (it fails INC2), the product isn't customer controlled (it fails INC3), or the product is not generally available (it fails INC4). Entries are disputed when there are differing opinions about it being a vulnerability or regarding the specific details of the vulnerability itself. The more binary cases of INC2, INC3, and INC4 are not things that can be disputed, per se. They either are or are not true.

**Comment by dadinolfi** [comment]
Updated CNA Rules draft.
