### ISSUE TITLE
Update CNT1

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#31]
GOAL:  Make the CNA Rules easier to use
CHANGE: Add extra decision for the case when issues aren't independently fixable and when you aren't sure.  These weren't carried over from the proposed changes document when we wrote the final draft.
OUTCOME:  
WORDING:
	CNT1:
		If a vulnerability can be fixed independently of the others, go to CNT2.
		If the vulnerabilities cannot be fixed independently, group the bugs together and go to CNT2.
If it is not clear whether the vulnerabilities can be fixed independently, group the bugs together and go to CNT2.

GOAL:  Make the CNA Rules easier to use
CHANGE:  CNT1 should merge vulnerabilities caused by the same type of mistake made in multiple locations of the code.  For example, using > instead of >= or not sanitizing URL parameters for XSS attacks.
OUTCOME:  CNAs will no longer have to spend the resources assigning IDs to vulnerabilities that will have the exact same description in the CVE entry.

**Comment by kurtseifried** [comment]
Also define... is not using it any more fixing it? because that's always the last resort available ...

**Comment by EvansJonathan** [comment]
You should not consider how the vulnerability gets fixed when deciding CNT1.  Instead, you ask if you could fix the vulnerability independent of the others  For example, it does not matter that by not using the product you are "fixing" three vulnerabilities.  What matters is if you had the source code, could implement a fix without fixing the others.

The first proposal recognizes that if you don't have access to the source code, you won't always have enough information to be certain if two issues are independently fixable.  This is basically MITRE's default position.

The second proposal recognizes that the same block of code could be copied in hundreds of locations in the code, and argues that the cost of assigning CVE IDs to each independently fixable vulnerability outweighs the benefit.

**Comment by ghost** [comment]
Perhaps we need some distinction between source is available and source is not available. source available makes all sorts of things possible with respect to this.

**Comment by chandanbn** [comment]
Since CVE IDs are assigned to **problems**, having the term 'fixable' can be misleading. CNAs have to assign CVEs to problems that may not even be fixable! 

My suggestions:

If a set of problems **always manifest together**, and are of the same **problem-type** and **impact** then group them together. If not break them into smaller groups until each group satisfies this rule. If this is unknown break them.

Examples:
Consider two off-by-one vulnerabilities where code contains <= instead of < in a for statement. Lets call them A and B.

If A can be triggered only on 32 bit platforms, B can be triggered only on 64bit platforms:

- Assign two IDs, since they can not manifest together.

If A existed since version 3, and B existed since version 4, both fixed in version 6:

- Assign two IDs, though both manifested together on version 4 and 5, on version 3 only one vulnerability manifested.

If A is in library call x() and B is in library call y():

- Assign two IDs, there can be some applications where only library call x() is used and hence only A would manifest in that application.

If A causes application crash, and B causes information leak:

- Assign two IDs, since impacts differ.

If A and B are in an open source application and if B can be optionally compiled (i.e., #ifdef):

- Assign two IDs.

If there is not enough information to determine if they **always manifest together**:

- Assign two IDs.

If we are merging a set of issues to assign a single CVE id, then all the following must be true:

1. same problem type
2. same impact
3. same affected products, versions, platforms
4. if consumers can pick and choose  (turn on and off, use or not use) components, modules, library calls then those have to be the same. 

If a CNA can make this determination then they can assign one CVE ID.
If CNAs can not make this determination or there are unknowns, then assign different CVE IDs.

In a closed source software, such similar issues are likely to always manifest together, as how a piece of code is instantiated is under the vendor's control. Consumers responding to these issues would only have one way to respond to such issues: either apply a common workaround or apply a single update.

In open source software, such a control may not be possible and assigning different IDs may be more desirable as different consumers may want to respond differently to different issues. Some may be affected by only a subset of issues and may chose to fix only the problems applicable to them.

So '**always manifest together**' rule would cater to both open source and closed source challenges.

**Comment by chandanbn** [comment]
In other words, instead of asking '**are they independently fixable**?', ask '**can the problems occur independently**?'. IMHO this is an easier to understand and answer that leads to consistent interpretations and assignments.

**Comment by EvansJonathan** [comment]
The proposed wording was used in v2.0 of the CNA Rules so I am closing this issue.
